empty_line = false

format = "$all"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
success_symbol = "[ğŸ‘‰](bold green)"
error_symbol = "[ğŸš¨](bold magenta)"
vicmd_symbol = "[âœŒï¸](bold green)"

[hostname]
ssh_only = true
